export interface Patient {
  id: string;
  susCardNumber: string;
  name: string;
  cpf: string;
  socialName?: string | null;
  birthDate: Date;
  race: string;
  sex: string;
  gender: string;
  sexuality: string;
  nationality: string;
  schooling: string;
  phone?: string | null;
  email?: string | null;
  motherName: string;
  fatherName?: string | null;
  isDeceased: boolean;
  monitoringType: string;
  zipCode?: string | null;
  state: string;
  city: string;
  neighborhood: string;
  street: string;
  houseNumber: string;
  complement?: string | null;
  createdBy: string;
  createdAt: Date;
  updatedBy?: string | null;
  updatedAt?: Date | null;
  deletedAt?: Date | null;
}
