Page:
  name: page
  in: query
  description: Page number for pagination.
  required: false
  schema:
    type: integer
    default: 1
    minimum: 1

Limit:
  name: limit
  in: query
  description: Number of items per page.
  required: false
  schema:
    type: integer
    default: 10
    minimum: 1
    maximum: 100

OrderBy:
  name: orderBy
  in: query
  description: Column name to order the results by. Must match a valid field of the resource.
  required: false
  schema:
    type: string

OrderDir:
  name: orderDir
  in: query
  description: Direction to order the results. Accepts 'asc' for ascending or 'desc' for descending order.
  required: false
  schema:
    type: string
    enum:
      - asc
      - desc

Search:
  name: search
  in: query
  description: Filter search string for relevant record fields.
  required: false
  schema:
    type: string

SearchBy:
  name: searchBy
  in: query
  description: The specific column to perform the search on. If provided, search will be restricted to this field.
  required: false
  schema:
    type: string

StartDate:
  name: startDate
  in: query
  description: Filter records created after this date (inclusive). Use ISO 8601 date-time format.
  required: false
  schema:
    type: string
    format: date-time

EndDate:
  name: endDate
  in: query
  description: Filter records created before this date (inclusive). Use ISO 8601 date-time format.
  required: false
  schema:
    type: string
    format: date-time

IncludeDeleted:
  name: includeDeleted
  in: query
  description: Flag to include soft-deleted records in the results.
  required: false
  schema:
    type: boolean
    default: false
