Page:
  name: page
  in: query
  description: Page number for pagination.
  required: false
  schema:
    type: integer
    default: 1
    minimum: 1

Limit:
  name: limit
  in: query
  description: Number of items per page.
  required: false
  schema:
    type: integer
    default: 10
    minimum: 1
    maximum: 100

Search:
  name: search
  in: query
  description: Filter search string for relevant record fields.
  required: false
  schema:
    type: string

IncludeDeleted:
  name: includeDeleted
  in: query
  description: Flag to include soft-deleted records in the results.
  required: false
  schema:
    type: boolean
    default: false

StartDate:
  name: startDate
  in: query
  description: Filter records created after this date (inclusive). Use ISO 8601 date-time format.
  required: false
  schema:
    type: string
    format: date-time

EndDate:
  name: endDate
  in: query
  description: Filter records created before this date (inclusive). Use ISO 8601 date-time format.
  required: false
  schema:
    type: string
    format: date-time
